

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_Ato.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Academia_AtoEntities : DbContext
{
    public Academia_AtoEntities()
        : base("name=Academia_AtoEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }

    public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<CategoriaGastos> CategoriaGastos { get; set; }

    public virtual DbSet<CategoriaIngresos> CategoriaIngresos { get; set; }

    public virtual DbSet<Estudiantes> Estudiantes { get; set; }

    public virtual DbSet<Gastos> Gastos { get; set; }

    public virtual DbSet<Ingresos> Ingresos { get; set; }

    public virtual DbSet<Personal> Personal { get; set; }

    public virtual DbSet<Recordatorios> Recordatorios { get; set; }

    public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }

    public virtual DbSet<Grupo> Grupo { get; set; }

    public virtual DbSet<Horario> Horario { get; set; }

}

}

