
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_Ato.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CategoriaGastos
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriaGastos()
        {

            this.Gastos = new HashSet<Gastos>();

        }

    [Required]
    [Display(Name = "Categoría del Gasto")]
    public int IdCategoria { get; set; }

    [Required(ErrorMessage = "El campo Nombre es Descripción.")]
    [Display(Name = "Descripción")]
    [StringLength(150, MinimumLength = 2, ErrorMessage = "El campo Descripción  debe tener entre 2 y 150 caracteres.")]
    public string Descripcion { get; set; }
    
    [Required(ErrorMessage = "El campo Fecha de Fecha es obligatorio.")]
    [Display(Name = "Fecha de Nacimiento")]
    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
    public System.DateTime FechaCreacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Gastos> Gastos { get; set; }

}

}
