
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_Ato.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Estudiantes
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Estudiantes()
    {

        this.Grupo = new HashSet<Grupo>();

    }


    public int IdEstudiante { get; set; }

    public string IdUsuario { get; set; }

    public string Nombre { get; set; }

    public string PrimerApellido { get; set; }

    public string SegundoApellido { get; set; }

    public string Cedula { get; set; }

    public System.DateTime FechaNacimiento { get; set; }

    public int Edad { get; set; }

    public string Genero { get; set; }

    public decimal Peso { get; set; }

    public decimal Altura { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Correo { get; set; }

    public string HistorialMedico { get; set; }



    public virtual AspNetUsers AspNetUsers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Grupo> Grupo { get; set; }

}

}
