
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_Ato.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Gastos
{
    [Key]
    [Required]
    public int IdGastos { get; set; }
    
    public string IdUsuario { get; set; }
    [Required]
    [Display(Name = "Categoría del Gasto")]
    public int IdCategoria { get; set; }
    
    [Required(ErrorMessage = "El campo Nombre es Descripción.")]
    [Display(Name = "Descripción")]
    [StringLength(150, MinimumLength = 2, ErrorMessage = "El campo Nombre debe tener entre 2 y 150 caracteres.")]
    public string Descripcion { get; set; }

    [Required(ErrorMessage = "El campo Monto es obligatorio.")]
    [Display(Name = "Monto")]
    [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
    [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "El campo Monto debe tener máximo 2 decimales.")]
    public decimal Monto { get; set; }


    [Required(ErrorMessage = "El campo Fecha es obligatorio.")]
    [Display(Name = "Fecha del Gastos")]
    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
    public System.DateTime FechaIngreso { get; set; }



    public virtual AspNetUsers AspNetUsers { get; set; }
 
    public virtual CategoriaGastos CategoriaGastos { get; set; }

}

}
