
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_Ato.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Horario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Horario()
    {

        this.Grupo = new HashSet<Grupo>();

    }


    public int IdHorario { get; set; }

    public string Dia { get; set; }

    public string Tiempo { get; set; }

    public string Hora { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Grupo> Grupo { get; set; }

}

}
