
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_Ato.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ingresos
{

    public int IdIngreso { get; set; }

    public string IdUsuario { get; set; }

    public int IdCategoria { get; set; }

    public string Descripcion { get; set; }

    public decimal Monto { get; set; }

    public System.DateTime FechaIngreso { get; set; }



    public virtual AspNetUsers AspNetUsers { get; set; }

    public virtual CategoriaIngresos CategoriaIngresos { get; set; }

}

}
