
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_Ato.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Personal
{

    public int IdPersonal { get; set; }

    public string IdUsuario { get; set; }

    public string Nombre { get; set; }

    public string PrimerApellido { get; set; }

    public string SegundoApellido { get; set; }

    public int Cedula { get; set; }



    public virtual AspNetUsers AspNetUsers { get; set; }

}

}
